version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    command: python3 -m flask run --host=0.0.0.0
    

  redis:
    image: redis

  sqlite3:
    container_name: sqlite3_container
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    ports:
      - '9000:9000' 
    volumes:
      - ./home/little/Documents/crazy-flaskchat/flaskbb/flaskbb.sqlite:/root/db
    restart: unless-stopped

